name:                infernal-bot
version:             0.1.0.0
github:              "githubuser/infernal-bot"
license:             BSD3
author:              "James Burton"
maintainer:          "james@jamesburton.dev"
copyright:           "2021 James Burton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/infernal-bot#readme>

dependencies:
- base >= 4.7 && < 5
- calamity >=0.1.30   && <0.1.31
- data-default
- data-flags
- di
- di-polysemy
- generic-lens
- lens
- polysemy
- polysemy-plugin
- text
- text-show
- aeson
- optparse-generic
- random
- time
- df1
- unboxing-vector
- persistent
- persistent-postgresql
- monad-logger
- conduit
- bytestring

library:
  source-dirs: src
  default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - DerivingVia
    - FlexibleContexts
    - FlexibleInstances
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MultiWayIf
    - NumericUnderscores
    - OverloadedLabels
    - OverloadedStrings
    - PartialTypeSignatures
    - PolyKinds
    - ScopedTypeVariables
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - ViewPatterns
  ghc-options:
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    - -Wall
    - -Wno-name-shadowing
    - -Wno-partial-type-signatures
    - -fplugin=Polysemy.Plugin

executables:
  infernal-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-name-shadowing
    - -Wno-partial-type-signatures
    - -fplugin=Polysemy.Plugin
    dependencies:
    - infernal-bot

tests:
  infernal-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - infernal-bot
